### ISSUE TITLE
Unification v1.0.0 checklist

### ISSUE THREAD

**Issue by ramizpolic** [openclarity/openclarity#810]
This tracks high level items for unification tasks and preparation for v1.0.0 release:
- [ ] docs - installation guide at https://openclarity.io/docs/getting-started/
- [ ] docs - feature comparison against VMClarity and KubeClarity
- [ ] docs - upgrade notice for VMClarity and KubeClarity users
- [ ] release v1.0.0 features - https://github.com/openclarity/openclarity/milestone/1
