### ISSUE TITLE
Post-unification v1.0.0 checklist

### ISSUE THREAD

**Issue by ramizpolic** [openclarity/openclarity#811]
This tracks high-level items for post-unification tasks and preparation for **v1.0.0 release**:
- [x] docs - initial documentation overhaul
- [x] docs - feature comparison against VMClarity and KubeClarity - will be included in release notes
- [x] docs - usage and upgrade notice for VMClarity and KubeClarity users - will be included in release notes
- [x] https://github.com/openclarity/openclarity/milestone/1
- [x] final pre-release testing & patching
